version: '3.1'

services:

  haproxy:
    image: haproxy:2.1.3-alpine
    ports:
      - "80:80"
    volumes:
        - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    deploy:
      labels: [drouter.auto_update=true]
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        failure_action: rollback
      restart_policy:
        max_attempts: 3
        condition: on-failure
    networks:
      - loadbalancer

# Create network mukananet
networks:
  loadbalancer:
    external: true

